"""
Report: PDF — Generate laporan audit dalam format PDF.
Menggunakan fpdf2 dengan desain professional.
"""
import os
from fpdf import FPDF
from config import REPORT_YEAR, LOGO_PATH, KOMPONEN_FISIK


class AuditPDFReport(FPDF):
    """Custom PDF report untuk audit laptop — desain professional."""

    # Warna tema
    PRIMARY = (41, 128, 185)      # Biru utama
    PRIMARY_DARK = (30, 95, 138)  # Biru gelap
    ACCENT = (52, 73, 94)         # Abu-gelap
    LIGHT_BG = (236, 240, 241)    # Abu terang
    WHITE = (255, 255, 255)
    BLACK = (33, 33, 33)
    GREEN = (39, 174, 96)
    RED = (231, 76, 60)
    ORANGE = (243, 156, 18)

    def __init__(self, data: dict):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.data = data
        self.set_auto_page_break(auto=True, margin=25)

    @staticmethod
    def _safe(text) -> str:
        """Sanitize text agar aman untuk font bawaan PDF (Latin-1)."""
        if not isinstance(text, str):
            text = str(text)
        return text.encode("latin-1", errors="replace").decode("latin-1")

    # ── Header & Footer ──────────────────────────────

    def header(self):
        if self.page_no() == 1:
            return  # Halaman 1 punya cover sendiri

        # Header halaman biasa
        self.set_fill_color(*self.PRIMARY)
        self.rect(0, 0, 210, 12, "F")

        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*self.WHITE)
        self.set_y(3)
        pic = self._safe(self.data.get("pic_asset", ""))
        kode = self._safe(self.data.get("kode_asset", ""))
        self.cell(0, 6, f"AUDIT REPORT | {kode} | {pic}", align="C")
        self.set_text_color(*self.BLACK)
        self.set_y(16)

    def footer(self):
        self.set_y(-15)
        self.set_draw_color(*self.LIGHT_BG)
        self.line(15, self.get_y(), 195, self.get_y())
        self.set_font("Helvetica", "", 7)
        self.set_text_color(150, 150, 150)
        self.cell(95, 10, f"Generated by Laptop Asset Audit System", align="L")
        self.cell(95, 10, f"Hal. {self.page_no()} / {{nb}}", align="R")

    # ── Helpers ───────────────────────────────────────

    def _section_header(self, title: str, icon: str = ""):
        """Header section dengan garis bawah berwarna."""
        self.ln(4)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*self.PRIMARY)
        label = f"{icon}  {title}" if icon else title
        self.cell(0, 8, self._safe(label), new_x="LMARGIN", new_y="NEXT")
        # Garis bawah
        y = self.get_y()
        self.set_draw_color(*self.PRIMARY)
        self.set_line_width(0.6)
        self.line(self.l_margin, y, 195, y)
        self.ln(4)
        self.set_text_color(*self.BLACK)

    def _info_row(self, label: str, value: str):
        """Baris info key-value dengan styling."""
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*self.ACCENT)
        self.cell(55, 7, self._safe(label), new_x="END")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.BLACK)
        self.cell(0, 7, self._safe(f":  {value}"), new_x="LMARGIN", new_y="NEXT")

    def _empty_line(self, height: float = 3):
        self.ln(height)

    # ── Build ─────────────────────────────────────────

    def build(self):
        """Bangun seluruh isi PDF."""
        self.alias_nb_pages()

        d = self.data

        # ═══════════════════════════════════════════════
        # COVER PAGE
        # ═══════════════════════════════════════════════
        self.add_page()

        # Background bar atas
        self.set_fill_color(*self.PRIMARY)
        self.rect(0, 0, 210, 55, "F")

        # Logo
        if os.path.exists(LOGO_PATH):
            try:
                self.image(LOGO_PATH, x=15, y=10, h=20)
            except Exception:
                pass

        # Judul
        self.set_y(62)
        self.set_font("Helvetica", "B", 22)
        self.set_text_color(*self.PRIMARY_DARK)
        self.cell(0, 12, "REPORT PEMERIKSAAN", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "B", 18)
        self.cell(0, 10, "AUDIT LAPTOP / PC", align="C", new_x="LMARGIN", new_y="NEXT")

        # Garis dekoratif
        self.ln(5)
        y = self.get_y()
        self.set_draw_color(*self.PRIMARY)
        self.set_line_width(1)
        self.line(60, y, 150, y)
        self.ln(10)

        # Info box
        self.set_fill_color(*self.LIGHT_BG)
        box_y = self.get_y()
        self.rect(30, box_y, 150, 48, "F")

        self.set_y(box_y + 5)
        self.set_font("Helvetica", "", 12)
        self.set_text_color(*self.ACCENT)

        pic = self._safe(d.get("pic_asset", "-"))
        kode = self._safe(d.get("kode_asset", "-"))
        jenis = self._safe(d.get("jenis_asset", "-"))
        tanggal = self._safe(d.get("tanggal", "-"))

        info_items = [
            ("PIC Asset", pic),
            ("Kode Asset", kode),
            ("Jenis Asset", jenis),
            ("Tanggal Audit", tanggal),
        ]
        for label, value in info_items:
            self.set_x(40)
            self.set_font("Helvetica", "B", 11)
            self.cell(45, 10, label, new_x="END")
            self.set_font("Helvetica", "", 11)
            self.cell(0, 10, f":  {value}", new_x="LMARGIN", new_y="NEXT")

        # Tahun di bawah
        self.ln(15)
        self.set_font("Helvetica", "B", 40)
        self.set_text_color(220, 220, 220)
        self.cell(0, 15, REPORT_YEAR, align="C", new_x="LMARGIN", new_y="NEXT")

        # ═══════════════════════════════════════════════
        # PAGE 2: INFORMASI UMUM + SISTEM
        # ═══════════════════════════════════════════════
        self.add_page()

        self._section_header("INFORMASI UMUM")
        self._info_row("PIC Asset", d.get("pic_asset", "-"))
        self._info_row("Kode Asset", d.get("kode_asset", "-"))
        self._info_row("Jenis Asset", d.get("jenis_asset", "-"))
        self._info_row("Lama Dibawa", d.get("lama_dibawa", "-"))
        self._info_row("Tanggal Audit", d.get("tanggal", "-"))

        self._section_header("INFORMASI SISTEM")
        self._info_row("Hostname", d.get("hostname", "-"))
        self._info_row("Username", d.get("username", "-"))
        self._info_row("OS", f"{d.get('os_name', '-')} (Build {d.get('os_build', '-')})")
        self._info_row("Vendor", d.get("vendor", "-"))
        self._info_row("Model", d.get("model", "-"))
        self._info_row("Serial Number", d.get("serial_number", "-"))

        self._section_header("HARDWARE")
        self._info_row("CPU", d.get("cpu_name", "-"))
        self._info_row("CPU Cores", f"{d.get('cpu_cores', '-')} core / {d.get('cpu_threads', '-')} thread")
        self._info_row("RAM", f"{d.get('ram_total_gb', '-')} GB")
        self._empty_line()

        # Storage table
        storage = d.get("storage", [])
        if storage:
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(*self.ACCENT)
            self.cell(55, 7, self._safe("Storage"), new_x="LMARGIN", new_y="NEXT")

            # Table header
            self.set_font("Helvetica", "B", 9)
            self.set_fill_color(*self.PRIMARY)
            self.set_text_color(*self.WHITE)
            self.cell(35, 7, "  Drive", fill=True, new_x="END")
            self.cell(35, 7, "Total (GB)", fill=True, align="C", new_x="END")
            self.cell(35, 7, "Terpakai (GB)", fill=True, align="C", new_x="END")
            self.cell(35, 7, "Bebas (GB)", fill=True, align="C", new_x="END")
            self.cell(30, 7, "Usage %", fill=True, align="C", new_x="LMARGIN", new_y="NEXT")
            self.set_text_color(*self.BLACK)

            for i, s in enumerate(storage):
                bg = self.LIGHT_BG if i % 2 == 0 else self.WHITE
                self.set_fill_color(*bg)
                self.set_font("Helvetica", "", 9)
                self.cell(35, 6, self._safe(f"  {s.get('drive', '?')}"), fill=True, new_x="END")
                self.cell(35, 6, self._safe(str(s.get("total_gb", "?"))), fill=True, align="C", new_x="END")
                self.cell(35, 6, self._safe(str(s.get("used_gb", "?"))), fill=True, align="C", new_x="END")
                self.cell(35, 6, self._safe(str(s.get("free_gb", "?"))), fill=True, align="C", new_x="END")
                self.cell(30, 6, self._safe(f"{s.get('percent_used', '?')}%"), fill=True, align="C", new_x="LMARGIN", new_y="NEXT")

        # Network
        self._empty_line(5)
        network = d.get("network", {})
        self._section_header("NETWORK")
        self._info_row("IP Address", ", ".join(network.get("ip_addresses", ["-"])))
        self._info_row("MAC Address", ", ".join(network.get("mac_addresses", ["-"])))

        # ═══════════════════════════════════════════════
        # BATTERY
        # ═══════════════════════════════════════════════
        bat = d.get("battery", {})
        if bat.get("has_battery"):
            self._section_header("BATTERY")

            # Battery health bar visual
            health_str = bat.get("health_percent", "N/A")
            self._info_row("Level Baterai", bat.get("percent", "N/A"))
            self._info_row("Status Charging", bat.get("charging_status", "N/A"))
            self._info_row("Design Capacity", bat.get("design_capacity_wh", "N/A"))
            self._info_row("Full Charge Cap.", bat.get("full_charge_capacity_wh", "N/A"))
            self._info_row("Battery Health", health_str)

            # Visual health bar
            try:
                health_val = float(health_str.replace("%", ""))
                self._empty_line(3)
                bar_x = self.l_margin + 55
                bar_y = self.get_y()
                bar_w = 100
                bar_h = 6

                # Background
                self.set_fill_color(*self.LIGHT_BG)
                self.rect(bar_x, bar_y, bar_w, bar_h, "F")

                # Fill
                if health_val >= 70:
                    self.set_fill_color(*self.GREEN)
                elif health_val >= 40:
                    self.set_fill_color(*self.ORANGE)
                else:
                    self.set_fill_color(*self.RED)
                fill_w = (health_val / 100) * bar_w
                self.rect(bar_x, bar_y, fill_w, bar_h, "F")

                # Border
                self.set_draw_color(180, 180, 180)
                self.set_line_width(0.2)
                self.rect(bar_x, bar_y, bar_w, bar_h, "D")
                self.ln(bar_h + 3)
            except (ValueError, TypeError):
                pass

        # ═══════════════════════════════════════════════
        # SECURITY
        # ═══════════════════════════════════════════════
        sec = d.get("security", {})
        self._section_header("SECURITY")
        self._info_row("Firewall", sec.get("firewall_status", "-"))
        self._info_row("Antivirus", sec.get("antivirus_name", "-"))
        self._info_row("Status AV", sec.get("antivirus_status", "-"))

        # ═══════════════════════════════════════════════
        # PENILAIAN KONDISI FISIK
        # ═══════════════════════════════════════════════
        self.add_page()
        self._section_header("PENILAIAN KONDISI FISIK")
        matriks = d.get("matriks_fisik", {})

        # Table header
        col_w1 = 85
        col_w2 = 85
        self.set_font("Helvetica", "B", 10)
        self.set_fill_color(*self.PRIMARY)
        self.set_text_color(*self.WHITE)
        self.cell(col_w1, 9, "  Komponen", fill=True, new_x="END")
        self.cell(col_w2, 9, "  Kondisi", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*self.BLACK)

        for i, komponen in enumerate(KOMPONEN_FISIK):
            kondisi = matriks.get(komponen, "-")

            # Alternate row color
            bg = self.LIGHT_BG if i % 2 == 0 else self.WHITE
            self.set_fill_color(*bg)
            self.set_font("Helvetica", "", 10)
            self.cell(col_w1, 8, self._safe(f"  {komponen}"), fill=True, new_x="END")

            # Warna status
            if kondisi == "Baik":
                self.set_text_color(*self.GREEN)
                status_icon = "[OK]"
            elif kondisi == "Rusak":
                self.set_text_color(*self.RED)
                status_icon = "[!!]"
            elif kondisi == "Lecet":
                self.set_text_color(*self.ORANGE)
                status_icon = "[!]"
            else:
                self.set_text_color(*self.BLACK)
                status_icon = ""

            self.set_font("Helvetica", "B", 10)
            self.cell(col_w2, 8, self._safe(f"  {status_icon} {kondisi}"), fill=True, new_x="LMARGIN", new_y="NEXT")
            self.set_text_color(*self.BLACK)

        # ═══════════════════════════════════════════════
        # SARAN & KELUHAN
        # ═══════════════════════════════════════════════
        saran = d.get("saran_keluhan", "").strip()
        if saran:
            self._empty_line(8)
            self._section_header("SARAN & KELUHAN")

            self.set_fill_color(*self.LIGHT_BG)
            box_y = self.get_y()
            self.set_font("Helvetica", "", 10)

            # Hitung tinggi teks
            # Gunakan multi_cell untuk wrap text
            x_start = self.l_margin + 2
            w = 170 - 4
            self.set_x(x_start)
            self.set_fill_color(*self.LIGHT_BG)

            # Background box
            lines = self._safe(saran).split("\n")
            line_count = 0
            for line in lines:
                line_count += max(1, int(len(line) / 80) + 1)
            box_h = max(line_count * 6 + 10, 20)
            self.rect(self.l_margin, box_y - 2, 170, box_h, "F")

            # Draw border
            self.set_draw_color(180, 180, 180)
            self.set_line_width(0.3)
            self.rect(self.l_margin, box_y - 2, 170, box_h, "D")

            self.set_xy(x_start, box_y + 2)
            self.multi_cell(w, 6, self._safe(saran))
            self.ln(5)

        # ═══════════════════════════════════════════════
        # LAMPIRAN FOTO
        # ═══════════════════════════════════════════════
        image_paths = d.get("image_paths", [])
        if image_paths:
            self.add_page()
            self._section_header("LAMPIRAN FOTO BUKTI FISIK")

            for i, img_path in enumerate(image_paths):
                if not os.path.exists(img_path):
                    continue

                if self.get_y() > 210:
                    self.add_page()

                self.set_font("Helvetica", "I", 9)
                self.set_text_color(100, 100, 100)
                self.cell(0, 5, self._safe(f"Foto {i+1}: {os.path.basename(img_path)}"),
                          new_x="LMARGIN", new_y="NEXT")
                self.set_text_color(*self.BLACK)

                try:
                    self.image(img_path, x=self.l_margin, w=170)
                    self.ln(8)
                except Exception:
                    self.set_font("Helvetica", "", 9)
                    self.set_text_color(*self.RED)
                    self.cell(0, 5, self._safe(f"[Error loading: {img_path}]"),
                              new_x="LMARGIN", new_y="NEXT")
                    self.set_text_color(*self.BLACK)

        # ═══════════════════════════════════════════════
        # SOFTWARE LIST
        # ═══════════════════════════════════════════════
        software = d.get("software_list", [])
        if software:
            self.add_page()
            self._section_header(f"DAFTAR SOFTWARE TERINSTALL ({len(software)} aplikasi)")
            self.set_font("Helvetica", "", 8)

            # 2 kolom
            col_w = 85
            left_col = software[:len(software)//2 + 1]
            right_col = software[len(software)//2 + 1:]

            for j in range(max(len(left_col), len(right_col))):
                if self.get_y() > 275:
                    self.add_page()
                    self._section_header(f"DAFTAR SOFTWARE (lanjutan)")
                    self.set_font("Helvetica", "", 8)

                bg = self.LIGHT_BG if j % 2 == 0 else self.WHITE
                self.set_fill_color(*bg)

                left_text = left_col[j] if j < len(left_col) else ""
                right_text = right_col[j] if j < len(right_col) else ""

                self.cell(col_w, 4, self._safe(f"  {left_text}"), fill=True, new_x="END")
                self.cell(col_w, 4, self._safe(f"  {right_text}"), fill=True, new_x="LMARGIN", new_y="NEXT")


def generate_pdf(data: dict, output_path: str):
    """
    Generate PDF report dari data audit.

    Args:
        data: dict gabungan data manual + scan
        output_path: path file PDF output
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf = AuditPDFReport(data)
    pdf.build()
    pdf.output(output_path)
